### ISSUE TITLE
Index out of range 

### ISSUE THREAD

**Issue by anujgupta82** [nzw0301/keras-examples#10]
Getting index out of range in Cell 8, keras-examples/CNN_MNIST.ipynb

The value of pos is getting computed to 51 and it complains that this value must be between 1 and 50

    
	for img_index, filters in enumerate(first_layer, start=1):

	    for filter_index, mat in enumerate(filters):

	        pos = (filter_index)*10+img_index

	        draw_digit(mat, nb_filters, show_size, pos)

	plt.show()

Now first layer has dimensions : (26,26,5) 
hence img_index goes from 1 to 26. 

filters has dimension (26,5) 
filter_index goes from 0 to 25. 

when filter_index = 5 and img_index = 1, pos = 51 and exception is raised

**Comment by anujgupta82** [comment]
I felt original code is a more convoluted way of writing the functionality. So I rewrote this as 

	def plotNNfilter(units):
	    
	    filters = units.shape[3]
	    n_rows = units.shape[0]
	    n_columns = units.shape[3]
	    
	    for j in range(n_rows):
		plt.figure(figsize=(20,20))
		for i in range(n_columns):
		    plt.subplot(n_rows, n_columns, i+1)
		    plt.title("Filter = %s" %i)
		    plt.imshow(units[j,:,:,i], interpolation="nearest", cmap="gray")
		plt.show()

then just pass the output of layer 1

     plotNNfilter(first_layer)

**Comment by nzw0301** [comment]
Thanks!
