### ISSUE TITLE
How to get topic distribution per document?

### ISSUE THREAD

**Issue by teucer** [nzw0301/keras-examples#11]
For each document there should be a topic distribution: in the current example I expect a numpy array of shape (8000, 20). 

How this can be calculated?

**Comment by nzw0301** [comment]
`theta` in cell 5 is the topic distribution of a document.

**Comment by teucer** [comment]
ok implemented something like this:
```
top_model = Model(inputs=prodLDA.input, outputs=prodLDA.get_layer(index=9).output)
doc_topic_arr = top_model.predict(x_train, batch_size=100)
```

is that correct. I think it should be `index=8` actually (?)

**Comment by nzw0301** [comment]
Yes, `index=8` is the correct index to obtain `theta`.
