### ISSUE TITLE
about the data

### ISSUE THREAD

**Issue by beyondacm** [nzw0301/keras-examples#7]
can you please tell me where to down load the "yellow.ja.txt" and "yellow.en.txt" ? I could not find them through internet

**Comment by nzw0301** [comment]
Thank you for your comment.

Arthur Conan Doyle's work: `The Adventure of the Yellow Face` .
`yellow.ja.txt` is a Japanese version from [here](http://www.aozora.gr.jp/cards/000009/files/43028_15653.html).
`yellow.en.txt` is a English version [here](http://www.gutenberg.org/files/834/834-h/834-h.htm).
